### PR TITLE
Implement markdown and yaml linting, prepare eslint infrastructure

### PR DESCRIPTION
**Pull request by dvonthenen**
This enables some linting/checks for Markdown, GH Action, YAML, and Shell Linting.

This introduces GitHub actions to check those things and allows users to check locally before submitting a PR. Running locally requires `docker`, but the user doesn't necessarily need to install or check manually before submitting a PR. To download all dependencies (ie `make check` = run all lints, checks), they can run `make ensure-deps` to download all dependencies, tools, and etc.

Addresses the following issues: https://github.com/deepgram/deepgram-js-sdk/issues/286 https://github.com/deepgram/deepgram-js-sdk/issues/285 https://github.com/deepgram/deepgram-js-sdk/issues/284

The updates to the Markdown are from the issues raised by the mdlint check.

If you don't feel this adds value to the project, feel free to close this PR and the issues as well.

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
I love the idea of linting the code, but I'm not sure this approach is best for a JavaScript project?

We don't use shell, or go, or yaml.

And we should be linting the JS/TS with the `eslint` package (and `prettier` if we want to be extra robust). There's also a markdownlint-cli npm package we can use if we want to lint markdown.

**Review by lukeocodes — CHANGES_REQUESTED** [review]
call me old fashioned but i have concerns about this tooling being part of my workflow.

there are so many lighter solutions inside the JS ecosystem that do not require docker to run :/

**Comment by dvonthenen** [comment]
Yup, I get it. It was the easiest lift without investing too much time (as in like 5mins). This isn't required for someone to open a PR as it will check in the GH action. If this is too much for the project to add, you can close this PR.

**Comment by dvonthenen** [comment]
> And we should be linting the JS/TS with the `eslint` package (and `prettier` if we want to be extra robust). There's also a markdownlint-cli npm package we can use if we want to lint markdown.

This doesn't tackle any JS linting.

**Review by naomi-lgbt — APPROVED** [review]
I hope you don't mind, but I didn't wanna just discard this entirely.

I pushed a commit to shift the runners into the JS ecosystem, and preserved the rules you configured. 💜

**Comment by dvonthenen** [comment]
Doesn't matter. It's your work and code.

**Pull request closed without merging**
